### ISSUE TITLE
Should Create/Submit Pull Request be combined?

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/WindowsCommunityToolkit-wiki#6]
We should also call out briefly more about the CLA and how that works for contributors that may be new to OSS in general.

**Comment by Kyaa-dost** [comment]
I am not certain about combining the create /submit page as it will be too much information on one page since the whole idea of the wiki was to keep it simple and clean. Again I am open to ideas if this is not an effective approach 🤔 

CLA added in #13
